### ISSUE TITLE
error: insert into "up_users" (...) - column "name" of relation "up_users" does not exist

### ISSUE THREAD

**Issue by ahamill85** [strapi/migration-scripts#36] opened 2022-08-18 22:35 UTC
### Required System information

- Node.js version: 16.17.0
- NPM version: 8.15.0
- Source Strapi version: 3.6.8
- Target Strapi version: 4.3.4
- Source Database: pgs
- Target Database: pgs
- Operating system: alpine
- Which script are you running: v3-sql-v4-sql

### Describe the bug

`const message = name === 'notice' ? new messages_1.NoticeMessage(length, messageValue) : new messages_1.DatabaseError(messageValue, length, name);
                                                                                                 ^

error: insert into "up_users" (...) - column "name" of relation "up_users" does not exist`

**Comment by derrickmehaffy** [comment] 2022-08-24 15:53
I have additional user context in my possession but I cannot share because it's private, if you need it to reproduce let me know.

**Comment by derrickmehaffy** [comment] 2022-09-30 14:10
I believe this is duplicate of #38

**Closed by derrickmehaffy** 2022-09-30 14:10 UTC
Labels: issue: bug, severity: medium, source: v3-SQL to v4-SQL, status: pending reproduction
